package CalcApp.CalcPackage;


/**
* CalcApp/CalcPackage/NegativeNumber.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* jueves 2 de marzo de 2023 16H31' CET
*/

public final class NegativeNumber extends org.omg.CORBA.UserException
{

  public NegativeNumber ()
  {
    super(NegativeNumberHelper.id());
  } // ctor


  public NegativeNumber (String $reason)
  {
    super(NegativeNumberHelper.id() + "  " + $reason);
  } // ctor

} // class NegativeNumber
