package CalcApp.CalcPackage;

/**
* CalcApp/CalcPackage/NegativeNumberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* jueves 2 de marzo de 2023 16H31' CET
*/

public final class NegativeNumberHolder implements org.omg.CORBA.portable.Streamable
{
  public CalcApp.CalcPackage.NegativeNumber value = null;

  public NegativeNumberHolder ()
  {
  }

  public NegativeNumberHolder (CalcApp.CalcPackage.NegativeNumber initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalcApp.CalcPackage.NegativeNumberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalcApp.CalcPackage.NegativeNumberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalcApp.CalcPackage.NegativeNumberHelper.type ();
  }

}
