package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* jueves 2 de marzo de 2023 16H31' CET
*/

public interface CalcOperations 
{
  float sum (float a, float b);
  float div (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
  float mul (float a, float b);
  float sub (float a, float b);
  double pwr (double a, double b);
  double sqr (double a) throws CalcApp.CalcPackage.NegativeNumber;
  double cqr (double b) throws CalcApp.CalcPackage.NegativeNumber;
  String dtb (int a);
  String dto (int a);
  String dth (int a);
  int mod (int a, int b);
} // interface CalcOperations
